### ISSUE TITLE
[OTHERS] - Change the `assigned_comment` message author

### ISSUE THREAD

**Issue by zzap** [takanome-dev/assign-issue-action#152]
### What would you like to share?

Hello,

Is it possible to change `assigned_comment` and `already_assigned_comment` author. It is set to repo owner at the moment and we (WordPress Documentation team) would love to make it obvious it is a bot. Thanks

### Would you like to work on this issue?

- [ ] Yes, I want to work on this issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by takanome-dev** [comment]
Hey @zzap, thanks for taking the time opening this issue.

> Is it possible to change assigned_comment and already_assigned_comment author. It is set to repo owner at the moment and we (WordPress Documentation team) would love to make it obvious it is a bot

Hum, do you have an example that I can take a look at? Because normally the author will be `github-action-[bot]`. See screenshot below from [this issue](https://github.com/takanome-dev/test-gh-actions/issues/5)

![2023-08-23_14-38](https://github.com/takanome-dev/assign-issue-action/assets/79809121/a6b5a3b0-68b2-45ce-8f69-b66a50417136)

Is that what you meant?

**Comment by takanome-dev** [comment]
Oh I see, thanks for the screenshot! 

I'm unable to address this immediately, but I'll ensure to look into it as soon as I can. Your understanding is much appreciated!

**Comment by takanome-dev** [comment]
Ah, I think I now why it has that behavior, @zzap.

It's because you didn't use `'${{ secrets.GITHUB_TOKEN }}'` as the value of `github_token` but another token that you probably generated.

If you use the default token, the author will be `github-action-[bot]` but if you generate that token manually and use it, the author will be the user that has generated that token.
Hopefully that makes sense.

Check out this issue -> https://github.com/takanome-dev/test-gh-actions/issues/19

**Comment by zzap** [comment]
Ah, makes sense. I'll try the default one. Thank you so much for looking into it 😊

**Comment by takanome-dev** [comment]
No worries 🙂 Let me know if it persist 

> **Note**
>
> `GITHUB_TOKEN` is automatically generated so you don't need to generate a token and add it in your secrets

**Comment by zzap** [comment]
You were right, it's token. Now it shows the bot as comment author. 

Thank you so much for your help.
