### ISSUE TITLE
Feature: Add `/assign-previous-commenter`

### ISSUE THREAD

**Issue by koppor** [takanome-dev/assign-issue-action#240]
### Type of feature

💡 Feature

### Current behavior

Contributor posts texts, because they is not aware of `/assign-me`:

![image](https://github.com/user-attachments/assets/4d197fc7-aa6c-4f86-9a11-23f8bf37712c)

There is no possiblity to comment something to have this magic of assignment (and unassignent aftter a timeout) working.

### Suggested solution

Add `/assign-previous-commenter` which triggers the assignment of the previous (!) comment.

Advanced version could be `/assign {url to issue comment}`

Example: 

    /assign https://github.com/JabRef/jabref/issues/10418#issuecomment-2401128647

This would then assign the poster of that comment to the current issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by koppor** [comment]
Maybe `/assign-last-commenter` is the better name - to have a clear indication who is meant.

**Comment by koppor** [comment]
OK, `previous` might be even better ^^

**Comment by takanome-dev** [comment]
I’ve opted for `/assign @<username>` (still in draft and untested) instead of `/assign-previous`.

The reason is simple:
- If two people comment on the same issue and you want to assign it to the first person, `/assign-previous` would assign it to the last commenter, which may not be what you intend.

Using the username directly gives more control. Thoughts?

**Comment by koppor** [comment]
> Using the username directly gives more control. Thoughts?

Very nice idea! I just didn't see this option 😅.
